import type { Event, MatchTimelineEvent } from "../types";

export const FALLBACK_FIXTURES: Event[] = [
  {
    idEvent: "2274995",
    strEvent: "Bolton Wanderers vs Barnsley",
    strLeague: "English League 1",
    idLeague: "4396",
    strHomeTeam: "Bolton Wanderers",
    strAwayTeam: "Barnsley",
    intHomeScore: null,
    intAwayScore: null,
    strStatus: "Not Started",
    strTimestamp: "2026-02-07T15:01:00",
    dateEvent: "2026-02-07",
    strTime: "15:01:00",
    idHomeTeam: "133606",
    strHomeTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/yvxxrv1448808301.png",
    idAwayTeam: "133630",
    strAwayTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/xvxsuv1447437855.png",
    strVenue: "Toughsheet Community Stadium",
    strCountry: "England",
    strThumb:
      "https://r2.thesportsdb.com/images/media/event/thumb/iw44lq1752495981.jpg",
    strDescriptionEN: null,
  },
  {
    idEvent: "2275013",
    strEvent: "Lincoln City vs Bolton Wanderers",
    strLeague: "English League 1",
    idLeague: "4396",
    strHomeTeam: "Lincoln City",
    strAwayTeam: "Bolton Wanderers",
    intHomeScore: null,
    intAwayScore: null,
    strStatus: "Not Started",
    strTimestamp: "2026-02-14T15:00:00",
    dateEvent: "2026-02-14",
    strTime: "15:00:00",
    idHomeTeam: "135900",
    strHomeTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/x46tji1719860130.png",
    idAwayTeam: "133606",
    strAwayTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/yvxxrv1448808301.png",
    strVenue: "LNER Stadium",
    strCountry: "England",
    strThumb:
      "https://r2.thesportsdb.com/images/media/event/thumb/zgawi01752496065.jpg",
    strDescriptionEN: null,
  },
];

export const FALLBACK_TIMELINE_EVENTS: MatchTimelineEvent[] = [
  {
    id: "1",
    type: "substitution",
    minute: "89'",
    team: "home",
    player1: "Gyokores",
    player2: "Odegard",
  },
  {
    id: "2",
    type: "goal",
    minute: "88'",
    team: "away",
    player1: "Ekitike",
    player2: "Sallah",
  },
  {
    id: "3",
    type: "yellow_card",
    minute: "78'",
    team: "home",
    player1: "Saliba",
  },
  {
    id: "4",
    type: "corner",
    minute: "74'",
    team: "home",
    description: "3rd corner",
  },
  {
    id: "5",
    type: "substitution",
    minute: "67'",
    team: "home",
    player1: "Rice",
    player2: "Zubemendi",
  },
  {
    id: "6",
    type: "substitution",
    minute: "67'",
    team: "away",
    player1: "Frimpong",
    player2: "Robertson",
  },
  {
    id: "7",
    type: "red_card",
    minute: "66'",
    team: "away",
    player1: "Van Dijk",
    description: "Sent Off",
  },
  { id: "8", type: "goal", minute: "55'", team: "home", player1: "Saka" },
  {
    id: "9",
    type: "corner",
    minute: "52'",
    team: "home",
    description: "5th corner",
  },
  {
    id: "10",
    type: "corner",
    minute: "48'",
    team: "away",
    description: "3rd Corner",
  },
  {
    id: "11",
    type: "corner",
    minute: "45+2'",
    team: "home",
    description: "2nd corner",
  },
  {
    id: "12",
    type: "substitution",
    minute: "45'",
    team: "away",
    player1: "Jones",
    player2: "Mcallister",
  },
  {
    id: "13",
    type: "yellow_card",
    minute: "44'",
    team: "home",
    player1: "Gabriel",
  },
  {
    id: "14",
    type: "injury",
    minute: "44'",
    team: "away",
    player1: "Jones",
    description: "Injured",
  },
  {
    id: "15",
    type: "corner",
    minute: "36'",
    team: "home",
    description: "1st corner",
  },
  {
    id: "16",
    type: "yellow_card",
    minute: "34'",
    team: "away",
    player1: "Konate",
  },
  {
    id: "17",
    type: "info",
    minute: "25'",
    team: "home",
    player1: "Gyokores",
    description: "VAR Check",
  },
  {
    id: "18",
    type: "corner",
    minute: "16'",
    team: "away",
    description: "2nd Corner",
  },
  {
    id: "19",
    type: "goal",
    minute: "12'",
    team: "home",
    player1: "Gyokores",
    player2: "Odegard",
  },
  {
    id: "20",
    type: "corner",
    minute: "3'",
    team: "away",
    description: "1st Corner",
  },
];
