import type { Event } from "../types";

export const INITIAL_SIMULATED_MATCHES: Event[] = [
  {
    idEvent: "sim-1",
    strEvent: "Arsenal vs Barcelona",
    strLeague: "UEFA Champions League",
    idLeague: "4480",
    strHomeTeam: "Arsenal",
    strAwayTeam: "Barcelona",
    intHomeScore: "2",
    intAwayScore: "1",
    strStatus: "63'",
    strTimestamp: "2026-02-06T20:00:00",
    dateEvent: "2026-02-06",
    strTime: "20:00:00",
    idHomeTeam: "133604",
    strHomeTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png",
    idAwayTeam: "133739",
    strAwayTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/e3e8jm1710341498.png",
    strVenue: "Emirates Stadium",
    strCountry: "England",
    strThumb: "",
    strDescriptionEN: null,
  },
  {
    idEvent: "sim-2",
    strEvent: "Real Madrid vs Bayern Munich",
    strLeague: "UEFA Champions League",
    idLeague: "4480",
    strHomeTeam: "Real Madrid",
    strAwayTeam: "Bayern Munich",
    intHomeScore: "1",
    intAwayScore: "1",
    strStatus: "HT",
    strTimestamp: "2026-02-06T20:00:00",
    dateEvent: "2026-02-06",
    strTime: "20:00:00",
    idHomeTeam: "133738",
    strHomeTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png",
    idAwayTeam: "133674",
    strAwayTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/dmkfzx1720529498.png",
    strVenue: "Santiago Bernabéu",
    strCountry: "Spain",
    strThumb: "",
    strDescriptionEN: null,
  },
  {
    idEvent: "sim-3",
    strEvent: "PSG vs Inter Milan",
    strLeague: "UEFA Champions League",
    idLeague: "4480",
    strHomeTeam: "Paris Saint-Germain",
    strAwayTeam: "Inter Milan",
    intHomeScore: "0",
    intAwayScore: "0",
    strStatus: "34'",
    strTimestamp: "2026-02-06T20:00:00",
    dateEvent: "2026-02-06",
    strTime: "20:00:00",
    idHomeTeam: "133714",
    strHomeTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/rwqrrq1473504808.png",
    idAwayTeam: "133676",
    strAwayTeamBadge:
      "https://r2.thesportsdb.com/images/media/team/badge/cfh3ow1695750909.png",
    strVenue: "Parc des Princes",
    strCountry: "France",
    strThumb: "",
    strDescriptionEN: null,
  },
];
